## cross validation

### evaluating model performance

comman way to we train our model and test then measure the accuracy

![img](11.png)

there are several ways to perform the traing steps, they are

## option 1

**use all available data for training and test on same dataset**

if train a math skill by 100 questions, then give test in that, its like open book exam so the child will possible to pass 100%.


![img](22.png)


In this case is not valid, its like overfitting, so 

## option 2

**split the datasets**

we split 70% for training,  30 % for testing,


![img](33.png)

![img](55.png)

in this also have conflicts like what happen if the 70% q are algebra and 30% q are calculas, so the model will fail.

## option 3

**k fold validation**

lets assume fold value is 5 , for the data set

![img](44.png)



In [40]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [41]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [42]:
import pandas as pd


df = pd.DataFrame(digits.data)
df

0    1     2     3     4     5   ...   58    59    60    61   62   63
0     0.0  0.0   5.0  13.0   9.0   1.0  ...  6.0  13.0  10.0   0.0  0.0  0.0
1     0.0  0.0   0.0  12.0  13.0   5.0  ...  0.0  11.0  16.0  10.0  0.0  0.0
2     0.0  0.0   0.0   4.0  15.0  12.0  ...  0.0   3.0  11.0  16.0  9.0  0.0
3     0.0  0.0   7.0  15.0  13.0   1.0  ...  7.0  13.0  13.0   9.0  0.0  0.0
4     0.0  0.0   0.0   1.0  11.0   0.0  ...  0.0   2.0  16.0   4.0  0.0  0.0
...   ...  ...   ...   ...   ...   ...  ...  ...   ...   ...   ...  ...  ...
1792  0.0  0.0   4.0  10.0  13.0   6.0  ...  2.0  14.0  15.0   9.0  0.0  0.0
1793  0.0  0.0   6.0  16.0  13.0  11.0  ...  6.0  16.0  14.0   6.0  0.0  0.0
1794  0.0  0.0   1.0  11.0  15.0   1.0  ...  2.0   9.0  13.0   6.0  0.0  0.0
1795  0.0  0.0   2.0  10.0   7.0   0.0  ...  5.0  12.0  16.0  12.0  0.0  0.0
1796  0.0  0.0  10.0  14.0   8.0   1.0  ...  8.0  12.0  14.0  12.0  1.0  0.0

[1797 rows x 64 columns]

In [43]:
df['target']=digits.target
df

0    1     2     3     4     5  ...    59    60    61   62   63  target
0     0.0  0.0   5.0  13.0   9.0   1.0  ...  13.0  10.0   0.0  0.0  0.0       0
1     0.0  0.0   0.0  12.0  13.0   5.0  ...  11.0  16.0  10.0  0.0  0.0       1
2     0.0  0.0   0.0   4.0  15.0  12.0  ...   3.0  11.0  16.0  9.0  0.0       2
3     0.0  0.0   7.0  15.0  13.0   1.0  ...  13.0  13.0   9.0  0.0  0.0       3
4     0.0  0.0   0.0   1.0  11.0   0.0  ...   2.0  16.0   4.0  0.0  0.0       4
...   ...  ...   ...   ...   ...   ...  ...   ...   ...   ...  ...  ...     ...
1792  0.0  0.0   4.0  10.0  13.0   6.0  ...  14.0  15.0   9.0  0.0  0.0       9
1793  0.0  0.0   6.0  16.0  13.0  11.0  ...  16.0  14.0   6.0  0.0  0.0       0
1794  0.0  0.0   1.0  11.0  15.0   1.0  ...   9.0  13.0   6.0  0.0  0.0       8
1795  0.0  0.0   2.0  10.0   7.0   0.0  ...  12.0  16.0  12.0  0.0  0.0       9
1796  0.0  0.0  10.0  14.0   8.0   1.0  ...  12.0  14.0  12.0  1.0  0.0       8

[1797 rows x 65 columns]

In [44]:
X= df.drop(df[['target']],axis='columns')
y=df.target

In [45]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [46]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

lr.score(X_test,y_test)

c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [47]:
svc=SVC()
svc.fit(X_train,y_train)

svc.score(X_test,y_test)

0.9916666666666667

In [48]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

rf.score(X_test,y_test)

0.9722222222222222

In [49]:
from sklearn.model_selection import KFold

kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [50]:
for train_idex,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_idex,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [51]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)  

In [52]:
#  example

print(get_score(lr,X_train,X_test,y_train,y_test))
print(get_score(rf,X_train,X_test,y_train,y_test))
print(get_score(svc,X_train,X_test,y_train,y_test))

c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667
0.9722222222222222
0.9916666666666667


![img](77.png)

In [53]:
from sklearn.model_selection import StratifiedKFold

folds= StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [54]:
# collect the scores of the model, because they give diff scores on each iterations(total fold = 3)

score_lr=[]
score_rf=[]
score_svc=[]

In [55]:
for train_index, test_index in folds.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    score_lr.append(get_score(lr, X_train, X_test, y_train, y_test))
    score_rf.append(get_score(rf, X_train, X_test, y_train, y_test))
    score_svc.append(get_score(svc, X_train, X_test, y_train, y_test))


c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [56]:
score_lr

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [57]:
score_rf

[0.9298831385642737, 0.9565943238731218, 0.9265442404006677]

In [58]:
score_svc

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

**we define one function to perform all model and get the scores then checks which is best classifier model for our task**

### instead of doing manaully , we use the cross val score method to get this.

In [59]:
from sklearn.model_selection import cross_val_score

cross_val_score(lr,X,y,cv=3)

c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92153589, 0.94156928, 0.91652755])

In [60]:
cross_val_score(rf,X,y,cv=3)

array([0.93155259, 0.95659432, 0.92654424])

In [61]:
cross_val_score(svc,X,y,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

**if we want use parameter tuning and take the average of scores which is best fit**

In [70]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),X, y, cv=10)
np.average(scores1)

0.8870484171322162

In [71]:
scores2 = cross_val_score(SVC(gamma='auto'), X, y,cv=3)
np.average(scores2)

0.4346132442960489

In [72]:
scores3 = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X, y ,cv=3)
np.average(scores3)

c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


0.9193099610461881

## Conclusion 

**Logistic is best fit**

**note: the scores will differ based on each iteration while train the model and parameter tunning**